Pig Stack Trace
---------------
ERROR 0: java.lang.IllegalStateException: Job in state DEFINE instead of RUNNING

org.apache.pig.backend.executionengine.ExecException: ERROR 0: java.lang.IllegalStateException: Job in state DEFINE instead of RUNNING
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.getStats(MapReduceLauncher.java:822)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.launchPig(MapReduceLauncher.java:452)
	at org.apache.pig.backend.hadoop.executionengine.HExecutionEngine.launchPig(HExecutionEngine.java:308)
	at org.apache.pig.PigServer.launchPlan(PigServer.java:1474)
	at org.apache.pig.PigServer.executeCompiledLogicalPlan(PigServer.java:1459)
	at org.apache.pig.PigServer.execute(PigServer.java:1448)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:488)
	at org.apache.pig.PigServer.executeBatch(PigServer.java:471)
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:172)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:235)
	at org.apache.pig.scripting.BoundScript.exec(BoundScript.java:277)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:101)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(/src/week2/python/demo.py:23)
	at org.python.pycode._pyx0.call_function(/src/week2/python/demo.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.apache.pig.scripting.jython.JythonScriptEngine$Interpreter.execfile(JythonScriptEngine.java:217)
	at org.apache.pig.scripting.jython.JythonScriptEngine.load(JythonScriptEngine.java:440)
	at org.apache.pig.scripting.jython.JythonScriptEngine.main(JythonScriptEngine.java:424)
	at org.apache.pig.scripting.ScriptEngine.run(ScriptEngine.java:310)
	at org.apache.pig.Main.runEmbeddedScript(Main.java:1079)
	at org.apache.pig.Main.run(Main.java:584)
	at org.apache.pig.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.IllegalStateException: Job in state DEFINE instead of RUNNING
	at org.apache.hadoop.mapreduce.Job.ensureState(Job.java:292)
	at org.apache.hadoop.mapreduce.Job.getTaskReports(Job.java:534)
	at org.apache.pig.backend.hadoop.executionengine.shims.HadoopShims.getTaskReports(HadoopShims.java:235)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher.getStats(MapReduceLauncher.java:801)
	... 40 more
================================================================================
Pig Stack Trace
---------------
ERROR 2244: Job failed, hadoop does not return any error message

org.apache.pig.backend.executionengine.ExecException: ERROR 2244: Job failed, hadoop does not return any error message
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:180)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:235)
	at org.apache.pig.scripting.BoundScript.exec(BoundScript.java:277)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:101)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(/src/week2/python/demo.py:23)
	at org.python.pycode._pyx0.call_function(/src/week2/python/demo.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.apache.pig.scripting.jython.JythonScriptEngine$Interpreter.execfile(JythonScriptEngine.java:217)
	at org.apache.pig.scripting.jython.JythonScriptEngine.load(JythonScriptEngine.java:440)
	at org.apache.pig.scripting.jython.JythonScriptEngine.main(JythonScriptEngine.java:424)
	at org.apache.pig.scripting.ScriptEngine.run(ScriptEngine.java:310)
	at org.apache.pig.Main.runEmbeddedScript(Main.java:1079)
	at org.apache.pig.Main.run(Main.java:584)
	at org.apache.pig.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
================================================================================
Pig Stack Trace
---------------
ERROR 2244: Job failed, hadoop does not return any error message

org.apache.pig.backend.executionengine.ExecException: ERROR 2244: Job failed, hadoop does not return any error message
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:180)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:235)
	at org.apache.pig.scripting.BoundScript.exec(BoundScript.java:277)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:101)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(/src/week2/python/demo.py:23)
	at org.python.pycode._pyx0.call_function(/src/week2/python/demo.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.apache.pig.scripting.jython.JythonScriptEngine$Interpreter.execfile(JythonScriptEngine.java:217)
	at org.apache.pig.scripting.jython.JythonScriptEngine.load(JythonScriptEngine.java:440)
	at org.apache.pig.scripting.jython.JythonScriptEngine.main(JythonScriptEngine.java:424)
	at org.apache.pig.scripting.ScriptEngine.run(ScriptEngine.java:310)
	at org.apache.pig.Main.runEmbeddedScript(Main.java:1079)
	at org.apache.pig.Main.run(Main.java:584)
	at org.apache.pig.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
================================================================================
Pig Stack Trace
---------------
ERROR 2244: Job failed, hadoop does not return any error message

org.apache.pig.backend.executionengine.ExecException: ERROR 2244: Job failed, hadoop does not return any error message
	at org.apache.pig.tools.grunt.GruntParser.executeBatch(GruntParser.java:180)
	at org.apache.pig.tools.grunt.GruntParser.parseStopOnError(GruntParser.java:235)
	at org.apache.pig.scripting.BoundScript.exec(BoundScript.java:277)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:101)
	at org.apache.pig.scripting.BoundScript.runSingle(BoundScript.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx0.f$0(/src/week2/python/demo.py:23)
	at org.python.pycode._pyx0.call_function(/src/week2/python/demo.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.apache.pig.scripting.jython.JythonScriptEngine$Interpreter.execfile(JythonScriptEngine.java:217)
	at org.apache.pig.scripting.jython.JythonScriptEngine.load(JythonScriptEngine.java:440)
	at org.apache.pig.scripting.jython.JythonScriptEngine.main(JythonScriptEngine.java:424)
	at org.apache.pig.scripting.ScriptEngine.run(ScriptEngine.java:310)
	at org.apache.pig.Main.runEmbeddedScript(Main.java:1079)
	at org.apache.pig.Main.run(Main.java:584)
	at org.apache.pig.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
================================================================================
Error before Pig is launched
----------------------------
ERROR 1121: Python Error. Traceback (most recent call last):
  File "/src/week2/python/demo.py", line 22, in <module>
    iter = results.result("f").iterator()
AttributeError: 'NoneType' object has no attribute 'iterator'

org.apache.pig.backend.executionengine.ExecException: ERROR 1121: Python Error. Traceback (most recent call last):
  File "/src/week2/python/demo.py", line 22, in <module>
    iter = results.result("f").iterator()
AttributeError: 'NoneType' object has no attribute 'iterator'

	at org.apache.pig.scripting.jython.JythonScriptEngine$Interpreter.execfile(JythonScriptEngine.java:249)
	at org.apache.pig.scripting.jython.JythonScriptEngine.load(JythonScriptEngine.java:440)
	at org.apache.pig.scripting.jython.JythonScriptEngine.main(JythonScriptEngine.java:424)
	at org.apache.pig.scripting.ScriptEngine.run(ScriptEngine.java:310)
	at org.apache.pig.Main.runEmbeddedScript(Main.java:1079)
	at org.apache.pig.Main.run(Main.java:584)
	at org.apache.pig.Main.main(Main.java:176)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: Traceback (most recent call last):
  File "/src/week2/python/demo.py", line 22, in <module>
    iter = results.result("f").iterator()
AttributeError: 'NoneType' object has no attribute 'iterator'

	at org.python.core.Py.AttributeError(Py.java:205)
	at org.python.core.PyObject.noAttributeError(PyObject.java:1013)
	at org.python.core.PyObject.__getattr__(PyObject.java:1008)
	at org.python.pycode._pyx0.f$0(/src/week2/python/demo.py:23)
	at org.python.pycode._pyx0.call_function(/src/week2/python/demo.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.apache.pig.scripting.jython.JythonScriptEngine$Interpreter.execfile(JythonScriptEngine.java:217)
	... 12 more
================================================================================
